name: Analyze Chess with Fairy-Stockfish

on:
  push:
    paths:
      - '**/*.pgn'
      - '**/*.ipynb'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔧 Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip python3-pip
          pip3 install --upgrade pip
          pip3 install python-chess papermill jupyter

      - name: 📥 Download Fairy-Stockfish
        run: |
          wget https://github.com/ianfab/Fairy-Stockfish/releases/download/fairy-stockfish%2F14.1/Fairy-Stockfish-14.1-Linux.zip
          unzip Fairy-Stockfish-14.1-Linux.zip -d fsf
          chmod +x fsf/fairy-stockfish-14.1-linux
          ls -l fsf  # Zeige Dateien zum Debuggen

      - name: 📊 Run Notebook with Papermill
        run: |
          papermill analyze_with_fairy_stockfish.ipynb output.ipynb
