name: Analyze with Lc0

on:
  push:
    paths:
      - '**.pgn'
      - '**.py'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          pip install python-chess

      - name: Download Lc0
        run: |
          wget https://github.com/LeelaChessZero/lc0/releases/download/v0.29.0/lc0-v0.29.0-linux.tar.gz
          tar -xzf lc0-v0.29.0-linux.tar.gz
          mv lc0-v0.29.0-linux lc0_dir

      - name: Download Lc0 Network
        run: |
          wget -O lc0_dir/network.pb.gz https://lczero.org/api/v2/networks/download/best

      - name: Run Analysis Script
        run: |
          python analyze_with_lc0.py
